name: vae
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.9
  - numpy
  - matplotlib
  - tqdm
  - pyyaml
  - joblib
  - scikit-learn
